apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: greeting-service:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
