name: CI Pipeline (Build & Push Only)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.FATMASLITI  }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build + push greeting-service
      - name: Build & push greeting-service image
        run: |
          docker build -t fatmasliti/greeting-service:latest ./greeting-service
          docker push fatmasliti/greeting-service:latest

      # Build + push quote-service
      - name: Build & push quote-service image
        run: |
          docker build -t fatmasliti/quote-service:latest ./quote-service
          docker push fatmasliti/quote-service:latest
